### ISSUE TITLE
U2 AP63205 Can suffer catastrophic failure under some circumstances

### ISSUE THREAD

**Issue by pii100** [VoronDesign/Voron-Tap#42]
Multiple reports of U2 releasing magic smoke in discord see https://discord.com/channels/460117602945990666/1058146062457643029

Suspected instability on Vin during power up causing oscillation leading to failure.

**Comment by tanaes** [comment]
We are currently tracking down the issue. This affects *all* V2 (24V-compatible) boards. **IT IS DANGEROUS** in that it can lead to an uncontrolled short in the failed regulator, so it is advised that people discontinue use of these boards immediately. Although we haven't heard of any failures yet when operated at 5V, it's completely possible that it could still happen, so we can't recommend using them as-is at 5V either at this time.

The reason we didn't catch this failure in testing is that it seems to be heavily setup-dependent, potentially due to variation in the electrical characteristics of the power connection. Thus, none of the ~250 boards I assembled and tested ever popped a regulator at my bench, but some of those same boards had their regulators fry when connected to someone else's printer.  

Unfortunately, that also suggests that these boards as-is are right on the edge of whatever instability causes the failure. Thus, even if you've installed one in your machine and it has been working fine to this point, it may still fail at some point down the line. I would not consider keeping one of these PCBs on my machine, personally.

I will be posting a full write-up here when we've fully diagnosed the issue, and in the meantime we are also working on a couple different approaches for board revisions that we will be testing ASAP.

Please follow the linked thread in Discord for additional info.

**Comment by tanaes** [comment]
# Update 4 Jan

Thanks to the incredible help of a bunch of talented and generous people in the Voron Discord, we have a candidate for a root cause of the failures as well as a corresponding interim solution that should at least *reduce* failures on V2.1 boards.

## Root cause candidate: inrush voltage spike

The vast majority of failures seem to occur on initial powerup of the sensor PCB, and so far all reported cases have happened when connected to 24V rather than 5 volts — especially when 'hot plugging' the board into an already-energized power rail. 

What appears to be happening is that inrush current (as the 22µF input decoupler capacitor is initially charged) combines with inductance in the power lines to cause a transient voltage spike at the Vin pin of the switching regulator IC. This happens because the electromagnetic field produced by current flowing through the power wires stores some amount of energy; once the input capacitor charges to 24V that electromagnetic field begins to collapse, dumping the energy back into the capacitor in the form of higher voltage. 

A Discord member demonstrated this using an LTSpice current simulation, using estimates for resistivity and inductance of 2m long 24 AWG power wires:

![tap_spice-simple](https://user-images.githubusercontent.com/8292608/210698758-11904884-6b51-4df3-a4d6-72ba7838a39b.png)

Discord member Ran_K updated this with a more realistic model incorporating DC bias in the actual input capacitor used, and showed that this could lead to even higher voltages, briefly exceeding 50 V. 

![tap_spice](https://user-images.githubusercontent.com/8292608/210699054-014945f1-05cd-438c-9366-8a056e185f9f.png)

They were able to subsequently demonstrate actual peak voltage of around 54V at Vin on an oscilloscope using a V2.1 board:

![tap_oscope_24V](https://user-images.githubusercontent.com/8292608/210699270-4372b36c-6655-4bfe-8e6a-5fac5bb35db2.jpg)

I was able to replicate this phenomenon on my own scope, in my case reaching a peak observed voltage of around 43V when hot-plugging into a 4A current-limited power supply set at 24V:

![SDS00035](https://user-images.githubusercontent.com/8292608/210699513-31a91992-0fa7-4abb-a98e-cfa8aaf81c6f.png)

By contrast, hot-plugging a 5V input gave a maximum voltage spike of under 10V:

![SDS00031](https://user-images.githubusercontent.com/8292608/210699758-6a1d0b7f-ab65-4910-b25e-c276c6e8f348.png)

These numbers seem to fit reasonably well with the observed patterns of failure that have been reported. The AP63205 regulator used on the V2.1 PCB has a datasheet maximum of 40V for transient spikes on Vin, which given the variation in actual electrical characteristics of peoples' specific setups (including likely lower inrush when not hot-plugging), helps explain why only a minority of boards have been reported as failing — as well as why setups that toast one board seem more likely to toast subsequent boards, as well. 

## Proposed interim solution

Adding a very small amount of series resistance to the +24V power connector may damp the inrush current sufficiently to reduce the transient voltage spike to safe levels without compromising the performance of the sensor. To test this, I made a wiring harness with a 1Ω wire-round resistor in-line on +24V wire. 

![IMG_0866](https://user-images.githubusercontent.com/8292608/210702550-7ab21d25-b941-4931-8f65-fda4fa6205e5.jpeg)

On the scope, using the same testing setup as above, you can see that this dropped my maximum voltage spike from 43V to about 30V — well under the datasheet maximum for the IC. 

![SDS00038](https://user-images.githubusercontent.com/8292608/210702816-b4dbd0d9-6997-4e27-810f-3ba49481fd60.png)

This setup only marginally reduced the steady-state voltage at Vin, with only an 18 mV drop with a supply of 5V:
![SDS00028](https://user-images.githubusercontent.com/8292608/210702928-8f5498df-4c20-4745-abe3-54d97370648d.png)

This suggests that using a 2.2Ω resistor would be an even better option. I didn't have a 2.2Ω wire-wound on hand, so I made another test harness using a small SMD chip resistor. (A thin film resistor is a poor choice for this in actual use, more on this later; however, it worked fine for a quick test.)

In the linked YouTube clip, you can see that repeatedly hot-plugging a board using the in-line resistor works totally fine, while the board without the in-line resistor fries after just a few tries:

[![Video link](https://img.youtube.com/vi/JJMcMZI8iz4/hqdefault.jpg)](https://youtu.be/JJMcMZI8iz4)

### How to modify your wiring harness

**This is a proposed band-aid, not a solution. Please be careful. If you have any doubts, there are a number of alternatives switching mechanisms for Tap available.**

Use a 2.2Ω wire-wound resistor. It is important to use a wire-wound resistor rather than the more common thin-film resistors because they have better power pulse characteristics. The resistor will briefly see a high-wattage pulse at powerup (perhaps  1-200W over 10 µs), and this can quickly break down thin-film resistors. 

Make sure to tin the wires and resistor leads before soldering them together:

![IMG_0865](https://user-images.githubusercontent.com/8292608/210704206-e9257c9b-591c-4ee2-a15e-2bd51c5b5ed4.jpeg)

Then heat shrink over the exposed leads to give them some strain relief and protection from shorting:

![IMG_0866](https://user-images.githubusercontent.com/8292608/210704275-aceb4ffa-539a-494e-8256-036728e5d173.jpeg)

## Other potential issues for revision

In addition to dealing with inrush on-board, we are looking at making some additional improvements in a revised board as soon as possible. These changes may include reverse polarity protection, improved regulator tuning, and broader sensor compatibility.

**Comment by tionebrr** [comment]
Hello folks,

The optical sensor open collector is directly exposed to that kind of issues too. It's risky. I would drive the line with something else than the sensor itself. Could be a mosfet (or a PNP) and a dedicated pullup, or an ESD protected logic buffer, whatever is the cheapest that fits the bill and the board. A simple resistor in serie would already give some protection.

For the VIN surge, the solution you implemented here is a simple RC filter which is the cheapest way to deal with it. A TVS diode would be a more serious protection. 
Also, if you put a fuse before the TVS, that fuse will get triggered in case of reverse polarity. It's not a perfect solution because of the fuse trip time, but this could be calculated and tested.

**Comment by skygrip** [comment]
Hi All,

What was the logic around using a Switch-mode power supply for whats effectively a 50ma optical switch? Surely a jellybean linear regulator like the LM7805 would be simpler, cheaper, and avoid any chip-shortage related supply chain issues. Linear regulators don't need high value decoupling capacitors, and have orders of magnitude better transient response.

**Comment by tionebrr** [comment]
I thought that too @skygrip

**Comment by tanaes** [comment]
Initially to allow operation from 5-24V while staying within the 4.7V datasheet minimum voltage for the OPB971 sensor. Also while 50 mA doesn't sound like a ton, using an LDO to drop from 24V still means dissipating close to a watt on a very small PCB in a hot chamber. That said, i've ordered an LDO-based prototype as well for evaluation in the next round. 

These issues are being discussed extensively on Discord, so I'd appreciate if you'd ping me there in the #24V OptoTap Board Troubleshooting thread in the #voron_tap channel so we can keep the signal:noise ratio on this issue high for people. Thanks!

**Comment by tionebrr** [comment]
The Voron Discord is mostly a user place. It's very noisy. Github is more practical for people who wants to contribute imho. 

There are optical sensor with forward current as low as 5mA. The board as of today may be too small for the protection and signal conditioning components anyway.

**Comment by JendaDH** [comment]
Hi, can't we just put bi-directional $1 TVS diode on the input and save the IC and other components from the peak voltage?

**Comment by tanaes** [comment]
# Issue resolution

After some extensive testing and lots of input, PR #53 should resolve this issue.

## Testing

To help with stress-testing the circuit, I put together a test rig using a rotary contactor. This allowed me to hot-connect up to eight boards in quick succession, and rack up thousands of individual tests across dozens of prototypes. (This also took a few iterations -- the first attempts, which connected the boards in parallel, didn't reliably reproduce the failures.)

[[Test setup and 5V]](https://imgur.com/e4ggTBc)

Using the test rig on the V2.1 boards, you can see the inrush voltage spike (and ringing) at 12V supply, with spike peaking at around 24V:

![SDS00006](https://user-images.githubusercontent.com/8292608/222799394-0013f8c0-61ba-4912-9555-09278fb41b6e.png)


### Testing original circuit

And at 24V, the inrush spike peaks at around 52V and immediately causes a short in the regulator, causing the power supply to go into current-limiting mode:

![SDS00008](https://user-images.githubusercontent.com/8292608/222799419-42a01d95-afea-4a52-8b1f-09f9a9d0d1cb.png)

Using this setup I was able to reliably fry the V2.1 boards in relatively short order. (Although it's worth noting that some individual boards survived a few dozen attempts before blowing.)

[[Frying boards]](https://imgur.com/axee4tO)


### Testing original circuit + series resistor

Using the same setup, a 2.2Ω series resistor dampens the circuit enough to basically eliminate the voltage spike.

![SDS00011](https://user-images.githubusercontent.com/8292608/222799670-2187df1e-c7cb-4cd4-a739-748561b1e98d.png)


I was unable to fry any of the original boards using the 2.2Ω in-line resistor. 

[[Testing in-line resistor]](https://imgur.com/cd0fLqe)

### Testing a revised circuit

The revised version of the circuit has a number of changes. For a full run-down, see the change log in the Readme. Two are especially relevant to this issue: 1) adding a polyfuse and 2) Schottky barrier diode into the Vin path.

The Schottky diode protects against accidental reverse polarity connection, as might happen if one were to accidentally swap Pwr and Gnd leads when connecting. Before, that would cause the regulator to immediately short.

The polyfuse does double duty. First, the low (1-6 Ω) resistance under normal operating conditions is enough to fully damp the system, eliminating the voltage spike. 

![SDS00013](https://user-images.githubusercontent.com/8292608/222799806-d1fb61b9-5613-45f6-8168-e6e9675181c1.png)


Second, in the case that something downstream did short, the polyfuse will increase resistance and limit the amount of current flowing through the device.

I have been unable kill any boards using this protection circuit:

[[Updated circuit testing]](https://imgur.com/RegJSfE)

### Real world release candidate testing

To gather some real-world testing, I sent about 20 release candidate boards out to testers to try on their machine. No one has seen any failures yet (despite some aggressive attempts), and the distribution of responses suggests that performance should be about the same as before. 

<img width="792" alt="Screen Shot 2023-03-02 at 2 41 06 PM" src="https://user-images.githubusercontent.com/8292608/222799895-3a47f28d-5da0-485d-a2b5-a96e7162a1f8.png">
<img width="807" alt="Screen Shot 2023-03-02 at 2 41 13 PM" src="https://user-images.githubusercontent.com/8292608/222799899-aad222ab-0a4c-45d2-91ed-797cccae7d17.png">


## Design considerations

### Linear regulator?

We actually initially considered a linear regulator for OptoTap. The low-noise and low complexity of an LDO is attractive for this kind of small low-power circuit. However, the minimum datasheet current requirements for the optical sensor suggests a total required heat dissipation of around a watt, which on paper puts it right at the edge of what would be viable in printers with higher chamber temps. 

However, I did go ahead and order some prototypes with an LDO for testing. These did indeed give about a 26°C ∆T over ambient. Although this would be perfectly fine in a room temperature environment, in a hot chamber and directly under a hot stepper motor it's right on the edge of what I'd be comfortable with. 

![FLIR0030](https://user-images.githubusercontent.com/8292608/222799949-3422c945-501d-4c02-895a-bcab8bde0d26.jpg)


### TVS diode?

I also tested incorporation of a TVS diode to clip voltage spikes. However, testing on the scope showed no performance advantage relative to just the polyfuse (with no spike there's nothing to clip). And given the relatively small amount of headroom between Vmax of the chip (32V) and working voltage (24V), a TVS diode with sufficiently high breakdown voltage to not leak at chamber temp may not have a sufficiently low clamping voltage to adequately protect the chip anyway. This problem is discussed in a very cromulent [application note](https://www.analog.com/media/en/technical-documentation/application-notes/an88f.pdf) from Analog Devices on this exact phenomenon. 

### Additional improvements

In addition to the protection components, the revised board incorporates better conditioning on Vout. The output capacitance has been doubled with the addition of a second capacitor, and the inductor has been changed from a small ferrite to a much better wirewound power inductor to avoid potential saturation of the coil. 

## Many thanks!

A *ton* of people contributed to the diagnosis and resolution of this problem. Thank you so much for your kind assistance!

Especially thanks to:

- TheProfessorBE
- Retsamedoc
- TheBrakShow
- Pi100
- RanK
- Boxxy
- BJH
- Shammy
- Mallcop
- Jade
- Bender
- Steve
- All the beta testers
- Anyone else slipping my mind right now

**Comment by tionebrr** [comment]
@tanaes and all the contributors, amazing work guys !

**Comment by hoeken** [comment]
I was thinking about using this chip on a completely unrelated board and found this page.  I love how you handled this so transparently so that others like me can learn from it.

**Comment by AlekseyMamontov** [comment]
Google brought me here too))
However, there is a great document that describes similar processes.
And everything can be solved simply by installing a capacitor.

[an88f (1).pdf](https://github.com/user-attachments/files/26321608/an88f.1.pdf)
