### ISSUE TITLE
jlcpcb - Incorrect Part Placement?

### ISSUE THREAD

**Issue by thijstriemstra** [VoronDesign/Voron-Tap#59]
hi @tanaes I submitted the bom and placement files for an order at jlcpcb (my first) and uploaded the files provided in https://github.com/VoronDesign/Voron-Tap/tree/main/OptoTap/Tap_Photosensor_PCB_v2/jlcpcb/production_files

They came back with the following issue though, so it seems the PCB placement is off or I did something wrong.. 

Their feedback:

> Since we are not so sure about the polarities of the components D1 are correct or not. Could you please kindly check if the polarities and placements of the components are correct in the below picture? Is it okay to proceed with production?

![jlcpcb feedback](https://user-images.githubusercontent.com/305679/233515164-3e01f607-c194-4da8-ab84-2875cafb0e23.JPG)

![smt top](https://user-images.githubusercontent.com/305679/233515541-128e74c6-1a9e-40b2-9246-d38be6ccd61d.png)

![sm original](https://user-images.githubusercontent.com/305679/233515993-2a9377b7-0818-4bf2-8988-0f06a3280a09.png)

**Comment by thijstriemstra** [comment]
> Since we are not so sure about the polarities of the components D1 are correct or not. Could you please kindly check if the polarities and placements of the components are correct in the below picture? Is it okay to proceed with production?

I opened the `Tap_Photosensor_PCB.kicad_pro` file in KiCad 7.0 and it shows the following schematic for D1:

<img width="791" alt="schematic1" src="https://user-images.githubusercontent.com/305679/234063657-51590d7f-eb2b-4f08-9725-1ce966da64df.png">

<img width="891" alt="schematic2" src="https://user-images.githubusercontent.com/305679/234062415-b36c0043-df6a-4074-8570-d43d6751198c.png">
 
I guess that'll be enough info for them to answer their question about D1, but I'll also include a [link to the kicad files](https://github.com/VoronDesign/Voron-Tap/tree/main/OptoTap/Tap_Photosensor_PCB_v2).

**Comment by tanaes** [comment]
The positive terminal should be in the upper left of the footprint in that picture — their “corrected” part is upside down.

**Comment by thijstriemstra** [comment]
thanks for the feedback @tanaes. they returned with:

![image](https://user-images.githubusercontent.com/305679/235326694-2070e7b2-3046-4549-8958-89c1292b1cb6.png)

**Comment by tanaes** [comment]
That is incorrect -- D1 should be rotated 180°. Pin 1 should be in the
upper right corner, as denoted by the corner mark in the silkscreen.

**Comment by thijstriemstra** [comment]
![IMG_4926](https://user-images.githubusercontent.com/305679/236202611-7127ec89-c862-432e-b2e9-cee7508de7d1.png)

thanks @tanaes, they came back with this, and it looks ok now right?

**Comment by tanaes** [comment]
That is correct!

On May 4, 2023, Github Notifications ***@***.***> wrote:
>

> thanks @tanaes <https://github.com/tanaes>, they came back with this,
> and it looks ok now right?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/VoronDesign/Voron-Tap/issues/59#issuecomment-
1534679256>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AB7ISADPAQJN5DDBKJCORGLXEONUNANCNFSM6AAAAAAXGGLK3I>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by thijstriemstra** [comment]
thanks for the help, the production started. how can we prevent this from happening to other users, it seems the jlcpcb .zip files in the repository produce incorrect jlcpcb instructions? can they updated? im not sure how because  i don't see an export to zip function in the jlcpcb interface..

**Comment by tanaes** [comment]
initially I think JLCPCB had incorrect pin numbering for this part in
their system, so what would happen is the original automated placement
would be correct but then they would go back and manually 'fix' it to be
backwards. My guess is that they have updated their database but that
has broken the rotation for that part in the file. I will need to re-
export and check again.

On May 4, 2023, Github Notifications ***@***.***> wrote:
> thanks for the help, the production started. how can we prevent this
> from happening to other users, it seems the jlcpcb .zip files in the
> repository produce incorrect jlcpcb instructions? can they updated? im
> not sure how because i don't see an export to zip function in the
> jlcpcb interface..
>

—
Reply to this email directly, view it on GitHub
<https://github.com/VoronDesign/Voron-Tap/issues/59#issuecomment-
1535589639>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AB7ISAGNZ733DGNNNSPNBK3XERJ3ZANCNFSM6AAAAAAXGGLK3I>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by thijstriemstra** [comment]
looks like this was fixed in https://github.com/VoronDesign/Voron-Tap/commit/e783ce8710ebc401b4b872ef84dd3216f443cf81, thanks!
