### ISSUE TITLE
Questions Regarding the Use of Voron-Tap

### ISSUE THREAD

**Issue by leeeboo** [VoronDesign/Voron-Tap#70]
Hello,

I've recently started using Voron-Tap and I have a couple of questions that I hope the community can help answer.

1. Does residual filament on the nozzle affect the z-offset? If so, how can this issue be addressed?
2. I tend to apply adhesive on the print bed during printing. Will this have any impact on the printing process?

I would appreciate any insight or advice on these matters.

Thank you!

**Comment by TheFuzzyGiggler** [comment]
1.) It will change your z-height but since the tap sensor is relative anyways it shouldn't affect it much unless the residual filament gets dislodged while running your homing macro. What I mean by relative is, that the Z height will be offset for every probe as long as that residual filament is attached. You should be rehoming between prints anyways so it shouldn't be a major issue.

2.) Nope, except you might get some adhesive on the nozzle where it taps the bed during probing. But I don't think that will be an issue really.
